// flow-typed signature: 49896d34cec81de2e9cabd3a17e64de9
// flow-typed version: <<STUB>>/karma-browserify_v^6.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-browserify/lib/bro' {
  declare module.exports: any;
}

declare module 'karma-browserify/lib/bundle-file' {
  declare module.exports: any;
}

declare module 'karma-browserify/lib/preprocessor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-browserify/index' {
  declare module.exports: $Exports<'karma-browserify'>;
}
declare module 'karma-browserify/index.js' {
  declare module.exports: $Exports<'karma-browserify'>;
}
declare module 'karma-browserify/lib/bro.js' {
  declare module.exports: $Exports<'karma-browserify/lib/bro'>;
}
declare module 'karma-browserify/lib/bundle-file.js' {
  declare module.exports: $Exports<'karma-browserify/lib/bundle-file'>;
}
declare module 'karma-browserify/lib/preprocessor.js' {
  declare module.exports: $Exports<'karma-browserify/lib/preprocessor'>;
}
