// flow-typed signature: 1382cdd662daa92be735649dd8bd099d
// flow-typed version: <<STUB>>/karma-babel-preprocessor_v^8.0.0-beta.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-babel-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-babel-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-babel-preprocessor/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-babel-preprocessor/lib/index' {
  declare module.exports: any;
}

declare module 'karma-babel-preprocessor/test/generator' {
  declare module.exports: any;
}

declare module 'karma-babel-preprocessor/test/generator.spec' {
  declare module.exports: any;
}

declare module 'karma-babel-preprocessor/test/hello' {
  declare module.exports: any;
}

declare module 'karma-babel-preprocessor/test/hello.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-babel-preprocessor/karma.conf.js' {
  declare module.exports: $Exports<'karma-babel-preprocessor/karma.conf'>;
}
declare module 'karma-babel-preprocessor/lib/index.js' {
  declare module.exports: $Exports<'karma-babel-preprocessor/lib/index'>;
}
declare module 'karma-babel-preprocessor/test/generator.js' {
  declare module.exports: $Exports<'karma-babel-preprocessor/test/generator'>;
}
declare module 'karma-babel-preprocessor/test/generator.spec.js' {
  declare module.exports: $Exports<'karma-babel-preprocessor/test/generator.spec'>;
}
declare module 'karma-babel-preprocessor/test/hello.js' {
  declare module.exports: $Exports<'karma-babel-preprocessor/test/hello'>;
}
declare module 'karma-babel-preprocessor/test/hello.spec.js' {
  declare module.exports: $Exports<'karma-babel-preprocessor/test/hello.spec'>;
}
